// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gozpucsbypqgoddzkuih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvenB1Y3NieXBxZ29kZHprdWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTQxNzksImV4cCI6MjA2NzQzMDE3OX0.0RDrgxJfEFKOFvRpsNSghUGJhIQ0SAZVHNUoEPb75yI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});